# Generated by Django 5.0.6 on 2024-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelor_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='NULL', upload_to='images/'),
        ),
    ]
