# Generated by Django 5.0.6 on 2024-05-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelor_projects', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.CharField(default='', max_length=30),
        ),
    ]
